name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Kopyala
      uses: actions/checkout@v4

    - name: Node.js Kurulumu
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Paketleri Kur ve Projeyi Senkronize Et
      run: |
        npm install
        npx cap sync android

    - name: JDK 11 Kurulumu
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: APK Derleme (Gradle)
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon

    - name: APK Dosyasını Kaydet
      uses: actions/upload-artifact@v4
      with:
        name: dijital-esnaf-defteri-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
